use_frameworks!

platform :ios, '8.0'

target 'HSYImageZoomToolsKit_Example' do
  pod 'HSYImageZoomToolsKit', :path => '../'

  target 'HSYImageZoomToolsKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    pod 'HSYMacroKit', :git=> 'https://github.com/huangsongyao/HSYMacroKit.git'
    pod 'HSYMethodsToolsKit', :git=> 'https://github.com/huangsongyao/HSYMethodsToolsKit.git'
    pod 'HSYToolsClassKit', :git=>'https://github.com/huangsongyao/HSYToolsClassKit.git'
    
  end
end
